### ISSUE TITLE
Library matching package:shared_preferences_tools/src/shared_preferences_tools_debug.dart not found

### ISSUE THREAD

**Issue by fmwww** [adsonpleal/shared_preferences_tools#4]
![WX20240519-091808@2x](https://github.com/adsonpleal/shared_preferences_tools/assets/11371523/8e047ce5-e567-46a1-86a6-2e33d5fca1ce)

**Comment by themightychris** [comment]
Anyone figure this out? I just installed the package today and immediately ran into this too

**Comment by adsonpleal** [comment]
Sorry the delay, somehow I wasn't getting the new issues notifications. 

Did you follow the [Getting started](https://github.com/adsonpleal/shared_preferences_tools/blob/main/packages/shared_preferences_tools/README.md#getting-started) section? 

You need to do this before using the extension:

```dart
Future<void> main() async {
  await SharedPreferencesToolsDebug.init();
  runApp(const YourApp());
}
```

BTW, we plan to merge this extension to the `shared_preferences` package, so you won't need to do this in the future.

You can check the open PR [here](https://github.com/flutter/packages/pull/6749).

**Comment by adsonpleal** [comment]
I also just pushed the `1.1.0` version, so there is no need to add `await SharedPreferencesToolsDebug.init();` anymore.
